// <auto-generated />
using GatewayServer.AsyncProxyConfig.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GatewayServer.AsyncProxyConfig.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260630073801_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GatewayServer.AsyncProxyConfig.Entities.ClusterDestinationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ClusterCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cluster_code");

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator_name");

                    b.Property<string>("HelthCheckPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("helth_check_path");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifierName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modifier_name");

                    b.Property<long>("ModifyDate")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("destination");
                });

            modelBuilder.Entity("GatewayServer.AsyncProxyConfig.Entities.ClusterEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClusterCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cluster_code");

                    b.Property<string>("ClusterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cluster_name");

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator_name");

                    b.Property<short>("EnabledHelthCheck")
                        .HasColumnType("smallint")
                        .HasColumnName("enabled_helth_check");

                    b.Property<int>("HelthCheckInterval")
                        .HasColumnType("integer")
                        .HasColumnName("helth_check_interval");

                    b.Property<string>("HelthCheckPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("helth_check_path");

                    b.Property<string>("HelthCheckPolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("helth_check_policy");

                    b.Property<int>("HelthCheckTimeout")
                        .HasColumnType("integer")
                        .HasColumnName("helth_check_timeout");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LoadBalancingPolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("load_balancing_policy");

                    b.Property<string>("ModifierName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modifier_name");

                    b.Property<long>("ModifyDate")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_date");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.HasKey("Id");

                    b.ToTable("cluster");
                });

            modelBuilder.Entity("GatewayServer.AsyncProxyConfig.Entities.RouteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClusterCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cluster_code");

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator_name");

                    b.Property<short>("IsDeleted")
                        .HasColumnType("smallint")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MatchMethods")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_methods");

                    b.Property<string>("MatchPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_path");

                    b.Property<string>("ModifierName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modifier_name");

                    b.Property<long>("ModifyDate")
                        .HasColumnType("bigint")
                        .HasColumnName("modify_date");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_name");

                    b.Property<string>("Transforms")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transforms");

                    b.HasKey("Id");

                    b.ToTable("route");
                });
#pragma warning restore 612, 618
        }
    }
}
